import { ModeToggle } from "@/components/ui/theme-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="flex h-screen flex-1 items-center justify-center">
        {children}
      </div>
      <div className="fixed right-5 top-5">
        <ModeToggle />
      </div>
    </>
  );
}
